import React, { useEffect, useState } from 'react'
import apiClient from '../api/apiClient'

function StatCard({ title, value, helper }) {
  return (
    <article className="rounded-2xl shadow-xl border border-slate-800 bg-slate-900/70 p-6">
      <p className="text-xs uppercase tracking-[0.18em] text-slate-400">{title}</p>
      <p className="mt-2 text-4xl font-extrabold text-white">{value}</p>
      <p className="mt-2 text-sm text-slate-400">{helper}</p>
    </article>
  )
}

export default function StatsPage() {
  const [stats, setStats] = useState({
    total_lectures_processed: 0,
    total_questions_generated: 0
  })
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')

  const loadStats = async () => {
    setLoading(true)
    setError('')

    try {
      const res = await apiClient.stats()
      setStats(res?.data?.data || {
        total_lectures_processed: 0,
        total_questions_generated: 0
      })
    } catch (err) {
      setError(err?.response?.data?.message || err?.message || 'Failed to load stats')
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    loadStats()
  }, [])

  return (
    <section className="min-h-[82vh] rounded-2xl shadow-xl border border-slate-800 bg-gradient-to-br from-slate-950 via-slate-900 to-slate-950 p-6 md:p-8">
      <header className="flex flex-col md:flex-row md:items-center md:justify-between gap-3">
        <div>
          <p className="text-xs tracking-[0.28em] uppercase text-cyan-300/90">Analytics</p>
          <h1 className="mt-2 text-3xl md:text-4xl font-extrabold text-white">Lecture Performance Dashboard</h1>
        </div>
        <button
          type="button"
          onClick={loadStats}
          disabled={loading}
          className="rounded-xl border border-slate-700 bg-slate-900 px-4 py-2 text-sm font-semibold text-slate-200 hover:border-cyan-400 hover:text-cyan-200 disabled:cursor-not-allowed disabled:text-slate-500"
        >
          {loading ? 'Refreshing...' : 'Refresh'}
        </button>
      </header>

      {error && (
        <div className="mt-4 rounded-xl border border-rose-700/40 bg-rose-900/20 px-3 py-2 text-sm text-rose-300">
          {error}
        </div>
      )}

      <div className="mt-6 grid grid-cols-1 md:grid-cols-2 gap-4">
        <StatCard
          title="Total Lectures Processed"
          value={stats.total_lectures_processed}
          helper="All lecture analysis records stored in the system."
        />
        <StatCard
          title="Total Questions Generated"
          value={stats.total_questions_generated}
          helper="MCQs + short questions + viva questions generated by AI."
        />
      </div>
    </section>
  )
}
